### ISSUE TITLE
Issue on IE

### ISSUE THREAD

**Issue by RobertasM** [intbot/ng2-pdfjs-viewer#60] opened 2019-11-27 13:28 UTC
hi,
I trying lib on IE and getting some errors. In modal I show a PDF viewer and when I close this modal I get errors in console: : '**Object doesn't support this action**' (compatibility.js (91,35)) and '**Unable to get property 'prototype' of undefined or null reference**' (ui_utils.js (776,51)). Maybe you know how to prevent or fix such errors?

![image](https://user-images.githubusercontent.com/31724417/69726923-2b3df200-112a-11ea-89bf-ddc9c18fcbd6.png)

**Comment by RobertasM** [comment] 2019-11-28 08:28
After more debugging I see that when I close modal it destroys PDF viewer and then those exceptions are thrown in console. Maybe its because the PDF viewer is destroyed but still some left code executing some missing/destroyed javascript code?

**Comment by codehippie1** [comment] 2020-01-03 19:17
@RobertasM Did you see issue - https://github.com/intbot/ng2-pdfjs-viewer/issues/13

**Comment by codehippie1** [comment] 2021-02-27 05:56
@RobertasM Closing this issues due to non-activities. Please feel to reopen and provide a sample reproducible code if it still persists.

**Closed by codehippie1** 2021-02-27 05:56 UTC
