### ISSUE TITLE
Difference in print documents - Chrome and IE11

### ISSUE THREAD

**Issue by juliaber2** [intbot/ng2-pdfjs-viewer#33] opened 2019-07-02 10:14 UTC
We generate PDFs and show in Chrome (74.0.3729.169 build) and IE11 (011.0.9600.19377 build) with the ng2-pdfjs-viewer component (3.4.8 version). Both of them show the same results and it's fine. But when we try to print documents, results of printing are different: after Chrome the resulting document looks the same as visible PDF, but in IE11 the resulting document content is shrunked (scaled down). We finished fixing the problem with updating viewer.css for IE. It there some right way to fix the problem without updates of ng2-pdfjs-viewer code ?

**Comment by codehippie1** [comment] 2019-07-02 20:39
Have you noticed the same issue on PDFJS viewer site (https://mozilla.github.io/pdf.js/web/viewer.html). If this is a problem underneath(As stated you fixed issue on viewer.css), I suggest you log a bug against PDFJS directly (https://github.com/mozilla/pdf.js)

I will include the fix as part of my PDFjs upgrades

**Comment by juliaber2** [comment] 2019-07-04 13:26
Hi,

I removed all my changes from viewer.css and also @page definition from
PDF document. There is the only one @page definition  in the viewer.js code:
















*PDFPrintService.prototype = {  layout: function layout() {
this.throwIfInactive();    var body = document.querySelector('body');
body.setAttribute('data-pdfjsprinting', true);    var hasEqualPageSizes =
this.pagesOverview.every(function (size) {      return size.width ===
this.pagesOverview[0].width && size.height ===
this.pagesOverview[0].height;    }, this);    if (!hasEqualPageSizes) {
  console.warn('Not all pages have the same size. The printed ' + 'result
may be incorrect!');    }    this.pageStyleSheet =
document.createElement('style');    var pageSize = this.pagesOverview[0];
  this.pageStyleSheet.textContent = '@supports ((size:A4) and (size:1pt
1pt)) {' + '@page { size: ' + pageSize.width + 'pt ' + pageSize.height +
'pt;}' + '}';    body.appendChild(this.pageStyleSheet);  },*

In all documents, I could find, is written that IE11 doesn't support the*
size parameter of @page descriptor: *https://caniuse.com/#search=%40page

The result stays the same.
My document in IE is scaled down.

I attached 2 documents -  examples of the same document printed by Chrome
and by IE.
To be honest, example from mozilla site makes the same result in Chrome and
In IE.

Julia

**Comment by codehippie1** [comment] 2019-07-05 18:17
@juliaber2 When you say "example from mozilla site makes the same result in Chrome and
In IE" - Did you mean the scaling down issue is not present on Mozilla's viewer?
As I am using Mozilla's viewer internally, it should behave the same. Can you check the same version of Mozilla's PDFJS viewer as mine and let me know if the issue is reproducible there.

As for the attached documents, how do I retrieve them?

**Comment by juliaber2** [comment] 2019-07-07 05:40
What version is used in your viewer ?
We took the latest one. Concerning files, I can put it on my Google disk
and grant you an access. is it suitable ?

**Comment by codehippie1** [comment] 2019-07-18 22:12
Sorry about late reply. Version is v2.2.171. Did you get the same error on the Demo site?

Url: https://ng2-pdfjs-viewer.azurewebsites.net/home

**Comment by codehippie1** [comment] 2019-07-22 15:06
Have you tried the demo site as commented above?

**Comment by juliaber2** [comment] 2019-07-22 18:39
Hi,
thank for being back. At the end we fixed the problem with cutting document
with change in viewer.css
- simply added to #printcontainer >div the following strings:

transform-origin: left top;
transform: scale(0.82);

But the real problem is that even with these changes print behavior in IE
is unpredictable, sometimes it works, sometimes it doesn't. We spent a week
and this damn IE gives different results.

**Comment by codehippie1** [comment] 2019-07-22 18:49
@juliaber2 Glad it worked for you. It is a pain to support IE, as the support for the browser has officially ended. Thanks for the tip. This issue is a good knowledge base for those who are struggling with this old monster.

**Comment by codehippie1** [comment] 2019-07-22 18:56
@juliaber2 Here is the Mozilla's link talking about supported browsers. It clearly states, IE is supported "Mostly" - Some missing features/defects have been reported, but no problems in general.

You may create an issue directly with PDFJS.

If IE is core to your business, a custom pdf product would be of better choice if you face several problems.

**Comment by codehippie1** [comment] 2019-07-30 16:52
Closing as this should be fixed in underlying viewerjs

**Closed by codehippie1** 2019-07-30 16:52 UTC
Labels: enhancement, good first issue
