### ISSUE TITLE
page number display on toolbar

### ISSUE THREAD

**Issue by anees-tricon** [intbot/ng2-pdfjs-viewer#170] opened 2021-09-21 14:51 UTC
Hi Team,

  I see some difference in the page number display section for certain pdf document. I just wanted to get some clarity on why this is happening. Could someone please help answer my query?

<img width="802" alt="Screenshot 2021-09-21 at 8 17 39 PM" src="https://user-images.githubusercontent.com/9270288/134193350-fce2e96a-6cba-4f0e-963a-5479ebd40684.png">

<img width="802" alt="Screenshot 2021-09-21 at 8 17 20 PM" src="https://user-images.githubusercontent.com/9270288/134193453-529aab50-4b2a-49d3-ac29-37538057a0f9.png">

In first case, current page number is in the input field. In second field current page is shown in the label section and the input field has some other value.

**Comment by codehippie1** [comment] 2022-05-03 23:25
Since you mentioned "certain pdf document", Can you set up a sample where issue is reproducible with said document?

**Comment by codehippie1** [comment] 2024-05-31 00:14
No follow-ups from reporter. Closing

**Closed by codehippie1** 2024-05-31 00:14 UTC
